version: '3.8'

services:
  vite-app:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "4173:4173"
    volumes:
      - .:/app
      - /app/node_modules
    command: ["npm", "run", "preview"]
